# Generated by Django 5.1.4 on 2026-04-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
