# Generated by Django 5.1.4 on 2026-04-04 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_financialrecord_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='created_by',
            field=models.ForeignKey(help_text='The user who originally created this transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
